#!/bin/bash
DECKNAME=$1
DECKURL=$2
cd tappedOutScraper
# wait
scrapy crawl tappedOutSpider -o spiderOutput.json -a url=$DECKURL
wait
cd ..
# wait
python C:/Users/aac52/Documents/StratusWalk/filter.py $DECKNAME
wait
python C:/Users/aac52/Documents/StratusWalk/format.py $DECKNAME